name: Docker Build
description: Build and push a Docker image
inputs:
  username:
    description: 'The username for docker login'
    required: true
  password:
    description: 'The password for docker login'
    required: true
  docker-repo:
    description: 'The docker container name'
    required: true
  tag:
    description: 'Tag for the Docker image'
    required: true
  dockerfile:
    description: 'The dockerfile name'
    required: false
    default: Dockerfile
  args:
    description: 'Example: --build-arg PROP1=123 --build-arg PROP2="abc"'
    required: false

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build Docker Image
      run: |
        docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.docker-repo }}:${{ inputs.tag }} ${{ inputs.args }} .
      shell: bash

    - name: Push Docker Image
      run: |
        docker push ${{ inputs.docker-repo }}:${{ inputs.tag }}
      shell: bash
