name: Build and Test
description: Build and test project
inputs:
  dotnet-version:
    description: 'The version of .NET to use'
    required: true
  project-path:
    description: 'The project path of .NET to use'
    required: true
  install-wasm-tools:
    description: 'Install wasm-tools workload (required for Blazor WASM AOT)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install wasm workload
      if: ${{ inputs.install-wasm-tools == 'true' }}
      run: dotnet workload install wasm-tools
      shell: bash

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project-path }}
      shell: bash

    - name: Build
      run: dotnet build ${{ inputs.project-path }} --no-restore --configuration Release
      shell: bash

#    - name: Run Unit Tests
#      run: dotnet test src/tests --configuration Release
#      shell: bash
