name: Deploy WebAPI to Homologation

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '/assets'
      - '/.github/dependabot.yml'
      - '/.github/workflows/cleanup.yml'
    branches:
      - homol

env:
  APP_NAME: api.allandeba.dev.br-homol
  DOCKER_REPO: allandeba/api.allandeba.dev.br
  DOCKER_TAG: homol-${{ github.sha }}
  DOCKERFILE: ./src/allandeba.dev.br.Api/Dockerfile
  DEPLOY_PORT: 9002
  HEALTH_CHECK_URL: https://hml-api.allandeba.dev.br
  PROJECT_PATH: ./src/allandeba.dev.br.Api
  ENVIRONMENT_FILE: /etc/environment_allandeba.dev.br_homologation
  DOTNET_VERSION: 8.0.x
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        uses: ./.github/actions/build-and-test
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          project-path: ${{ env.PROJECT_PATH }}

      - name: Docker Build and Push
        uses: ./.github/actions/docker-build
        with:
          tag: ${{ env.DOCKER_TAG }}
          docker-repo: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ${{ env.DOCKERFILE }}

      - name: Deploy to Homologation Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST_PRD }}
          username: ${{ secrets. SERVER_USERNAME_PRD }}
          password: ${{ secrets.SERVER_PASSWORD_PRD }}
          script: |
            docker pull ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
            docker rm -f ${{ env.APP_NAME }} || true
            docker run -d --restart=always --name ${{ env.APP_NAME }} -p ${{ env.DEPLOY_PORT }}:8080 --env-file=${{ env.ENVIRONMENT_FILE }} ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}

      - name: Check status
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.HEALTH_CHECK_URL }}
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
          retry-all: true

      - name: Tag as Stable
        if: success()
        run: |
          docker tag ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_REPO }}:homol-stable
          docker push ${{ env.DOCKER_REPO }}:homol-stable

  rollback:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Rollback to Previous Version
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST_PRD }}
          username: ${{ secrets. SERVER_USERNAME_PRD }}
          password: ${{ secrets.SERVER_PASSWORD_PRD }}
          script: |
            docker rm -f ${{ env.APP_NAME }} || true

            # Capture the output of the docker run command
            output=$(docker run -d --restart=always --name ${{ env.APP_NAME }} -p ${{ env.DEPLOY_PORT }}:8080 --env-file=${{ env.ENVIRONMENT_FILE }} ${{ env.DOCKER_REPO }}:homol-stable 2>&1)
            echo "$output"

            # Check if the warning is in the output
            if echo "$output" | grep -qE "WARNING|Error"; then
              echo "Error encountered. Failing the job."
              exit 1
            fi
